version: '3.9'

services:
  database:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
